name: 'Firebase App Distribution'
description: 'GitHub Action that uploads artifacts to Firebase App Distribution'
author: 'Wojciech Zięba <@wzieba>'
inputs:
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  token:
    description: 'Upload token - see Firebase CLI Reference'
    required: false
  serviceCredentialsFile:
    description: 'Service credentials file'
    required: false
  serviceCredentialsFileContent:
    description: 'Content of service credentials file'
    required: false
  file:
    description: 'Artifact to upload (.apk or .ipa)'
    required: true
  groups:
    description: 'Distribution groups'
    required: false
  testers:
    description: 'Distribution testers'
    required: false
  releaseNotes:
    description: 'Release notes visible on release page'
    required: false
  releaseNotesFile:
    description: 'Release notes visible on release page'
    required: false    
  debug:
    description: 'Flag that can included to print verbose log output.'
    required: false
    default: false
outputs:
  console_uri:
    description: 'Console url'
  testing_uri:
    description: 'Testing url'
  binart_download_uri:
    description: 'Binary download url'
branding:
  color: 'orange'
  icon: 'send'
runs:
  using: 'docker'
  image: 'Dockerfile'
